---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  /api/signup:
    post:
      summary: Creates a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
      responses: 
        '201':
          description: Created
  /api/login:
    post:
      summary: login a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
      responses: 
        '201':
          description: Created
  /api/logout:
    delete:
      summary: Logout from account.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                
      responses: 
        '201':
          description: Created
  /api/forgot_password:
    post:
      summary: user forgets password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
      responses: 
        '201':
          description: Created
  /api/reset_password:
    post:
      summary: user reset password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    reset_password_token:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
      responses: 
        '201':
          description: Created  
  /leaves:
    get:
      summary: Retrieve a list of leaves
      tags:
        - Leaves API
      responses:
        '200':
          description: Successful response
        '500':
          description: Internal server error

    post:
      summary: Create a new leave
      description: Use this API to create a new leave.
      tags:
        - Leaves API
      requestBody:
              required: true
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      leave:
                        type: object
                        properties:
                          leave_details:
                            type: string
                          leave_type:
                            type: string
                          from_date:
                            type: string
                          to_date:
                            type: string
                          apply_to:
                            type: string
                          reason:
                            type: string
      responses:
        '201':
          description: Leave created successfully
        '400':
          description: Invalid request
        '500':
          description: Internal server error
  /leaves/{id}:
    get:
      summary: Show a leave
      tags:
        - Leaves API
      parameters:
        - name: id
          in: path
          description: ID of the leave to show
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
        '404':
          description: Leave not found
        '500':
          description: Internal server error
    put:
      summary: update leaves.
      tags:
        - Leaves API
      parameters:
        - name: id
          in: path
          description: ID of the leave to update
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                leave:
                        type: object
                        properties:
                          leave_details:
                            type: string
                          leave_type:
                            type: string
                          from_date:
                            type: string
                          to_date:
                            type: string
                          leave_status:
                            type: string
                          reason:
                            type: string
                          user_id:
                            type: string
      responses: 
        '201':
          description: Created 
    
    delete:
      summary: delete leaves.
      tags:
        - Leaves API
      parameters:
        - name: id
          in: path
          description: ID of the leave to update
          required: true
          schema:
            type: integer
      responses: 
        '201':
          description: Created 
  /statuses:
    get:
      summary: Retrieve a list of statuses
      tags:
        - Status API
      responses:
        '200':
          description: Successful response
        '500':
          description: Internal server error

    post:
      summary: add a new status
      description: Use this API to create a new status.
      tags:
        - Status API
      requestBody:
              required: true
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      status:
                        type: object
                        properties:
                          to:
                            type: string
                          cc:
                            type: string
                          status_date:
                            type: string
                          tasks_attributes:
                            type: object
                            properties:
                              working_hours:
                                type: string
                              task_status:
                                type: string
                              task_description:
                                type: string
                              billing_hours:
                                type: string
                              project_id:
                                type: string
      responses:
        '201':
          description: status created successfully
        '400':
          description: Invalid request
        '500':
          description: Internal server error
  /statuses/{id}:
    get:
      summary: Show a status.
      tags:
        - Status API
      parameters:
        - name: id
          in: path
          description: ID of the leave to update
          required: true
          schema:
            type: integer                
      responses: 
        '201':
          description: Created
    put:
      summary: update Status.
      tags:
        - Status API
      parameters:
        - name: id
          in: path
          description: ID of the leave to update
          required: true
          schema:
            type: integer  
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                        type: object
                        properties:
                          to:
                            type: string
                          cc:
                            type: string
                          status_date:
                            type: string
                          tasks_attributes:
                            type: object
                            properties:
                              working_hours:
                                type: string
                              task_status:
                                type: string
                              task_description:
                                type: string
                              billing_hours:
                                type: string
                              project_id:
                                type: string
      responses: 
        '201':
          description: Created 
    
    delete:
      summary: delete Status.
      tags:
        - Status API
      parameters:
        - name: id
          in: path
          description: ID of the leave to update
          required: true
          schema:
            type: integer
      responses: 
        '201':
          description: Created 
  
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
