---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  /api/signup:
    post:
      summary: Creates a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
      responses: 
        '201':
          description: Created
  /api/login:
    post:
      summary: login a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
      responses: 
        '201':
          description: Created
  /api/logout:
    delete:
      summary: Logout from account.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                
      responses: 
        '201':
          description: Created
  /api/forgot_password:
    post:
      summary: user forgets password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
      responses: 
        '201':
          description: Created
  /api/reset_password:
    post:
      summary: user reset password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    reset_password_token:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
      responses: 
        '201':
          description: Created
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
